name: flutter_widgets_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #国际化
  flutter_localizations:
    sdk: flutter
  fluro: ^1.6.3
  # 二维码生成器
  qr_flutter: ^3.2.0
  # 网络请求 
  dio: ^3.0.8
  #上拉加载下拉刷新
  # pull_to_refresh: ^1.6.3
  #状态管理
  provider: ^4.3.1
  #国际化
  intl_utils: ^1.9.0
  #事件传递
  event_bus: ^1.1.1
  #简易弹框
  easy_alert: ^0.0.8
  # 轮播图
  flutter_swiper: ^1.1.6
  cupertino_icons: ^1.0.0
  #一个优秀的动画库
  flutter_spinkit: ^4.1.2+1

  outline_material_icons: ^0.1.0

  flutter_staggered_animations: "^0.1.2"
  #高德地图
  amap_flutter_map: ^1.0.2
  #百度地图
  flutter_baidu_mapapi_map: ^2.0.0
  flutter_baidu_mapapi_utils: ^2.0.0
  flutter_baidu_mapapi_search: ^2.0.0
  share: ^0.6.1+1
  # 权限请求
  permission_handler: ^5.0.1+1
  # 保存图片/文件到本地
  image_gallery_saver: ^1.5.0
  #城市页面列表
  azlistview: ^1.1.0
  lpinyin: ^1.1.0
  #扫码
  qr_code_scanner: ^0.3.5
  #自定义键盘
  cool_ui: "^0.6.1"
  #感应器
  sensors_plus: ^0.6.0
  # snake: ^0.1.0

  #滚动到制定位置播放
  inview_notifier_list: ^1.0.0
  video_player: ^0.10.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/2.0x/
    - lib/assets/3.0x/
    - lib/assets/json/
    - lib/pages/baidu_map/files/
    - lib/pages/baidu_map/resoures/bmflocaltileimage/16/
    - lib/pages/baidu_map/resoures/bmflocaltileimage/17/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
